spring:
  application:
    name: yon2meet-backend
  liquibase:
    change-log: classpath:/db/db.changelog-main.yaml
kakao:
  client:
    id: FIXME
    secret: FIXME
jwt:
  secret-key: FIXME
  token-validity-in-seconds: 86400
server:
  port: 5000
